---
title: Junteng Liu
description: Personal Homepage of Junteng Liu, PhD Candidate in NLP at HKUST
url: https://lafayeheather89-del.github.io/LJT-Homepage
baseurl: "/LJT-Homepage"
# Site navigation
nav:
  - name: About
    url: /
  - name: Publications
    url: /publications/

# Author/Organization info to be displayed in the templates
author:
  name: Junteng Liu
  url: https://lafayeheather89-del.github.io/LJT-Homepage
  email: jliugi@connect.ust.hk
  github: Vicent0205
  google_scholar: https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate
  twitter: junteng88716710

# Collection settings
collections:
  posts:
    output: true
  publications:
    output: true
    permalink: /publications/:path/

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach: false
port: 4000
host: 0.0.0.0
baseurl: "" # does not include hostname

# Outputting
encoding: utf-8
future: true
unpublished: false

---